# tensorflow 101

In [1]:
import tensorflow as tf
import numpy as np

Create `tf.placeholder` objects - these will hold data

In [2]:
A = tf.placeholder(tf.float32, 
                  shape=(2,2),
                  name='A')
A.shape, A.name

(TensorShape([Dimension(2), Dimension(2)]), 'A:0')

In [3]:
v = tf.placeholder(tf.float32)
v.shape, v.name

(TensorShape(None), 'Placeholder:0')

In [4]:
w = tf.matmul(A, v)
w

<tf.Tensor 'MatMul:0' shape=(2, ?) dtype=float32>

All of the work happens in a "session", including feeding the variables values

In [11]:
v_val = np.array([7, 9])
v_val.shape, v_val[:, np.newaxis].shape

((2,), (2, 1))

Because TF does real matrix multiplication the dimensions of v must be right. Numpy normally takes care of that.

In [35]:
A_val = np.array([[0, 1], [1, 0]])
v_val = np.array([7,9])
print(v_val)
v_val = v_val[:, np.newaxis]
print(v_val)

[7 9]
[[7]
 [9]]


In [12]:
with tf.Session() as session:
    output = session.run(w, feed_dict={A: A_val, v: v_val})
    print(output, type(output))

[[ 9.]
 [ 7.]] <class 'numpy.ndarray'>


The update parameters are declared with objects of type `tf.Variable`. These have an initial value and must be initialised. (`global_variables_initializer` return object `init` which is called during the session) 

In [37]:
x = tf.Variable(tf.random_normal((3,3)))
t = tf.Variable(0)

In [42]:
init = tf.global_variables_initializer()
for i in range(5):
    with tf.Session() as session:
        output = session.run(init)
        print(i, output)
        print('x={}\nt={}'.format(x.eval(), t.eval()))

0 None
x=[[ 0.18194143  0.08420689 -0.08919143]
 [ 0.53497124  0.71285301  1.52758944]
 [-0.77104366  0.46912023 -1.05669296]]
t=0
1 None
x=[[  6.79584265e-01  -2.87745327e-01   5.15237212e-01]
 [  2.69078702e-01   1.91260493e-04   1.69554815e-01]
 [ -1.31525218e+00   1.99083865e-01   1.11669995e-01]]
t=0
2 None
x=[[-1.30924523  0.91284472 -1.15417194]
 [-1.08578694 -0.86057609 -0.82481891]
 [ 0.0456745  -0.84932929 -0.16622588]]
t=0
3 None
x=[[ 0.56091011  2.50249267  0.56520599]
 [-0.31054732 -0.89017075  0.68200004]
 [-0.6025601  -1.77790916 -0.36598784]]
t=0
4 None
x=[[-0.68452376  0.70998955 -0.5109849 ]
 [-1.49396873 -0.45116776 -0.60409343]
 [ 0.81177384  1.26929975 -0.65172076]]
t=0


A simple minimization example

In [44]:
u = tf.Variable(20.0)
cost = u*u + 4*u + 4

Instead of writing the update equations, choose an optimizer

In [45]:
learning_rate = 0.2
train_op = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [52]:
init = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(init)
    for i in range(30):
        session.run(train_op)
        print('i: cost {:.4f}, u {:.4f}'.format(cost.eval(), u.eval()))

i: cost 174.2400, u 11.2000
i: cost 62.7264, u 5.9200
i: cost 22.5815, u 2.7520
i: cost 8.1293, u 0.8512
i: cost 2.9266, u -0.2893
i: cost 1.0536, u -0.9736
i: cost 0.3793, u -1.3841
i: cost 0.1365, u -1.6305
i: cost 0.0492, u -1.7783
i: cost 0.0177, u -1.8670
i: cost 0.0064, u -1.9202
i: cost 0.0023, u -1.9521
i: cost 0.0008, u -1.9713
i: cost 0.0003, u -1.9828
i: cost 0.0001, u -1.9897
i: cost 0.0000, u -1.9938
i: cost 0.0000, u -1.9963
i: cost 0.0000, u -1.9978
i: cost 0.0000, u -1.9987
i: cost 0.0000, u -1.9992
i: cost 0.0000, u -1.9995
i: cost 0.0000, u -1.9997
i: cost 0.0000, u -1.9998
i: cost 0.0000, u -1.9999
i: cost 0.0000, u -1.9999
i: cost 0.0000, u -2.0000
i: cost 0.0000, u -2.0000
i: cost 0.0000, u -2.0000
i: cost 0.0000, u -2.0000
i: cost 0.0000, u -2.0000
